### ISSUE TITLE
Fix flakey SDK test cases 

### ISSUE THREAD

**Issue by Chrylo** [eclipse-kuksa/kuksa-android-sdk#85]
**Describe the bug**
The issue #45 introduced the configuration cache. All flakey tests have become even more flakey with this change.

**To Reproduce**
1. `./gradlew test -Dkotest.tags="!CustomDatabroker"

**Expected behavior**
Consistent successful test builds

**Comment by wba2hi** [comment]
Issue here seems to be, that due to the introduction of the configuration-cache the 'testDebugUnitTest' and 'testReleaseUnitTest' tasks are called and executed in parallel. Meaning the same tests might run at the same time against the same databroker. This may lead to conflicts with our current assertions (e.g. on how many callbacks should be received, or what value a vssPath should have after an update)

When using the --no-configuration-cache flag less tasks are executed in parallel and the above mentioned tasks are ran consecutively so mostly no conflicts happen. In rare cases there is still a test which is failing. These tests should be identified and adapted in a more robust way.

Possible solutions:
- don't share the same Databroker instance but create a separate Databroker instance for each testset, e.g. with different port
- re-write tests to better deal with parallel access, e.g. try not to depend on checking the received number of answers 
- make the testDebugUnitTest and testReleaseUnitTest reliably run consecutively instead of parallel
- remove or disable either of testDebugUnitTest / testReleaseUnitTest because right now they share the same testSet anyway (since our testSet might change, this solution should only be a last resort / temporary solution)
